### ISSUE TITLE
Docker compose

### ISSUE THREAD

**Issue by SergioEstebanP** [SergioEstebanP/DomoticPi#3]
**Description:** Orchestrate docker backend containers with docker compose files. 

**Subtasks:**
- [x] Create docker network.
- [x] Communicate each container by host name within the same net. 
- [x] Apply this behavior to all services and document the process.

----
**Links:**

- [Father task](https://github.com/SergioEstebanP/DomoticPi/projects/3#card-26969652)
